Repository PlayEveryWare/eos_plugin_for_unity, pull requests merged in 2024-03, with the labels that each got.

#550 tool: Added pull-patrol workflow
  .github/workflows/pull-patrol.yml
Labels: enhancement, build

#555 feat: Updates to EOSEditorWindow
  Assets/Plugins/Source/Editor/Windows/EOSEditorWindow.cs
Labels: enhancement

#558 fix: resolve errors where types only availabe in the Unity Editor were
  Assets/Plugins/Source/Core/Config.cs
  Assets/Plugins/Source/Core/EOSCreateOptions.cs
  Assets/Plugins/Source/Core/PlatformManager.cs
  Assets/Plugins/Windows/WindowsPlatformSpecifics.cs
Labels: bug

#564 fix: Rectified regression concerning the EOSBootstrapper and the EOS overlay.
  Assets/Plugins/Source/Editor/Build/BuildRunner.cs
  Assets/Plugins/Source/Editor/Build/EACPostBuild.cs
  Assets/Plugins/Source/Editor/Build/PlatformSpecificBuilder.cs
  Assets/Plugins/Windows/Editor/WindowsBuilder.cs
Labels: fix

#573 ui: Monospace font for log window.
  Assets/Prefab/UIDemoCanvasTemplate.prefab
  Assets/Resources/OFL.txt
  Assets/Resources/OFL.txt.meta
  Assets/Resources/SourceCodePro.ttf
  Assets/Resources/SourceCodePro.ttf.meta
Labels: enhancement, unresolved

#580 fix: Update documentation links & Support Information
  README.md
  docs/Walkthrough.md
  docs/add_plugin.md
  docs/apple_signin.md
  docs/command_line_export.md
  docs/configure_plugin.md
  docs/contributions.md
  docs/dev_env/HyperV_Linux_Guest_VM.md
  docs/dev_env/Ubuntu_Development_Environment.md
  docs/docs_on_docs/doc_style_guide.md
  docs/frequently_asked_questions.md
  docs/iOS/README_iOS.md
  docs/macOS/README_macOS.md
  docs/overlay.md
  docs/player_authentication.md
  docs/samples.md
  docs/scene_walkthrough/P2P_netcode_walkthrough.md
  docs/scene_walkthrough/P2P_walkthrough.md
  docs/scene_walkthrough/achievements_walkthrough.md
  docs/scene_walkthrough/auth&friends_walkthrough.md
  docs/scene_walkthrough/customInvites_walkthrough.md
  docs/scene_walkthrough/leaderboards_walkthrough.md
  docs/scene_walkthrough/lobbies_walkthrough.md
  docs/scene_walkthrough/metrics_walkthrough.md
  docs/scene_walkthrough/player_data_storage_walkthrough.md
  docs/scene_walkthrough/player_reports_and_sanctions_walkthrough.md
  docs/scene_walkthrough/sessions_and_matchmaking_walkthrough.md
  docs/scene_walkthrough/store_walkthrough.md
  docs/scene_walkthrough/title_storage_walkthrough.md
  docs/standards.md
  docs/steam.md
Labels: documentation
