Repository PlayEveryWare/eos_plugin_for_unity, pull requests merged in 2024-10, with the labels that each got.

#943 fix(login): Fix RefreshToken Login
  com.playeveryware.eos/Runtime/Core/EOSManager.cs
Labels: fix, tracked, plugin_issue

#942 Unwrap `WrappedPlatformOptions`
  com.playeveryware.eos/Runtime/Core/EOSManager.cs
Labels: fix, tracked, plugin_issue

#947 fix: Android Threading & IO in Unity
  Assets/Plugins/Android/Core/AndroidFileIOHelper.cs
  com.playeveryware.eos/Runtime/Core/Config/Config.cs
  com.playeveryware.eos/Runtime/Core/EOSManager.cs
  com.playeveryware.eos/Runtime/Core/PlatformSpecifics.cs
  com.playeveryware.eos/Runtime/Core/Utility/FileSystemUtility.cs
Labels: fix, tracked

#944 feat: Authentication Listener knows the difference between a Connect and Auth login
  Assets/Scripts/StandardSamples/Services/AchievementsService.cs
  Assets/Scripts/StandardSamples/Services/EOSService.cs
  Assets/Scripts/StandardSamples/Services/PlayerDataStorageService.cs
  Assets/Scripts/StandardSamples/Services/StatsService.cs
  Assets/Scripts/StandardSamples/UI/Common/SampleMenu.cs
  com.playeveryware.eos/Runtime/Core/AuthenticationListener.cs
Labels: enhancement, tracked

#955 Fix: `IOSBuilder` not using correct `FileSystemUtility` class
  Assets/Plugins/Source/Editor/Platforms/iOS/IOSBuilder.cs
Labels: fix

#937 Config Validation Unit tests
  Assets/Tests/PlayMode/Config/EOSConfigTests.cs
  Assets/Tests/PlayMode/Config/EOSConfigTests.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes/ExpandFieldAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/ExpandFieldAttribute.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes/FieldValidator.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/FieldValidator.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes/FieldValidatorAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/FieldValidatorAttribute.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes/GUIDFieldValidatorAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/GUIDFieldValidatorAttribute.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes/NonEmptyStringFieldValidatorAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/NonEmptyStringFieldValidatorAttribute.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes/SandboxIDFieldValidatorAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/SandboxIDFieldValidatorAttribute.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/EOSConfig.cs
Labels: tracked, unit-testing

#959 Improve menu
  Assets/Plugins/Source/Editor/EditorWindows/CheckDeploymentWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/CreatePackageWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSPluginSettingsWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSSettingsWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSUnitTestSettingsWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/InstallEOSZipWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/LogLevelWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/PluginVersionWindow.cs
  Assets/Plugins/Source/Editor/Utility/CreateXMLLinkUtility.cs
  Assets/Plugins/Source/Editor/Utility/MakefileUtility.cs
  Assets/Plugins/Source/Editor/Utility/SigningUtility.cs
  Assets/Tests/Editor/UnitTestResultsWindow.cs
  com.playeveryware.eos/Documentation~/command_line_export.md
  com.playeveryware.eos/Documentation~/configure_plugin.md
  com.playeveryware.eos/Documentation~/creating_the_upm_package.md
  com.playeveryware.eos/Documentation~/dev_env/Ubuntu_Development_Environment.md
  com.playeveryware.eos/Documentation~/easy_anticheat_configuration.md
  com.playeveryware.eos/Documentation~/frequently_asked_questions.md
  com.playeveryware.eos/Documentation~/getting_started_guide/README.md
  com.playeveryware.eos/Documentation~/getting_started_guide/plugin_eosconfiguration.png
  com.playeveryware.eos/Documentation~/images/create-package-menu.png
  com.playeveryware.eos/Documentation~/images/dev-portal-configuration-editor-menu.png
  com.playeveryware.eos/Documentation~/macOS/README_macOS.md
  com.playeveryware.eos/Documentation~/upgrading_to_new_versions_of_eos.md
Labels: UI, tracked

#961 integrate/Integrate 1.16.4
  Assets/Plugins/Linux/libEOSSDK-Linux-Shipping.so
  Assets/Plugins/Windows/x64/EOSSDK-Win64-Shipping.dll
  Assets/Plugins/Windows/x86/EOSSDK-Win32-Shipping.dll
  Assets/Plugins/iOS/EOSSDK.framework/EOSSDK
  Assets/Plugins/iOS/EOSSDK.framework/Info.plist
  Assets/Plugins/macOS/libEOSSDK-Mac-Shipping.dylib
  com.playeveryware.eos/Runtime/EOS_SDK/Generated/AntiCheatCommon/AntiCheatCommonGameRoundCompetitionType.cs
  com.playeveryware.eos/Runtime/EOS_SDK/Generated/AntiCheatCommon/AntiCheatCommonGameRoundCompetitionType.cs.meta
  com.playeveryware.eos/Runtime/EOS_SDK/Generated/AntiCheatCommon/AntiCheatCommonInterface.cs
  com.playeveryware.eos/Runtime/EOS_SDK/Generated/AntiCheatCommon/LogGameRoundStartOptions.cs
  com.playeveryware.eos/Runtime/EOS_SDK/Generated/ExternalCredentialType.cs
  com.playeveryware.eos/Runtime/EOS_SDK/Generated/P2P/ConnectionClosedReason.cs
  com.playeveryware.eos/Runtime/EOS_SDK/Generated/P2P/P2PInterface.cs
  com.playeveryware.eos/Runtime/EOS_SDK/Generated/P2P/RelayControl.cs
  com.playeveryware.eos/Runtime/EOS_SDK/Generated/Platform/InitializeThreadAffinity.cs
  com.playeveryware.eos/Runtime/EOS_SDK/Generated/Platform/PlatformInterface.cs
  com.playeveryware.eos/Runtime/EOS_SDK/Generated/PlayerDataStorage/PlayerDataStorageInterface.cs
  com.playeveryware.eos/Runtime/EOS_SDK/Generated/TitleStorage/TitleStorageInterface.cs
  com.playeveryware.eos/Runtime/EOS_SDK/Generated/Ui/SetToggleFriendsButtonOptions.cs
  com.playeveryware.eos/Runtime/EOS_SDK/Generated/Version/VersionInterface.cs
  com.playeveryware.eos/Runtime/EOS_SDK/Overrides/GetNextReceivedPacketSizeOptions.cs
  com.playeveryware.eos/Runtime/EOS_SDK/Overrides/GetNextReceivedPacketSizeOptions.cs.meta
  etc/PlatformSpecificAssets/EOS/Android/dynamic-stdc++/aar/eos-sdk.aar
  etc/PlatformSpecificAssets/EOS/Android/static-stdc++/aar/eos-sdk.aar
  tools/bin/EOSBootstrapper.exe
  tools/bin/EOSBootstrapperTool.exe
Labels: tracked

#962 feat(connect,google) : Connect Login with Google ID
  Assets/Plugins/Android/Core/AndroidConfig.cs
  Assets/Plugins/Android/login.java
  Assets/Plugins/Android/login.java.meta
  Assets/Plugins/Android/mainTemplate.gradle
  Assets/Plugins/Source/Editor/Platforms/Android/AndroidConfigEditor.cs
  Assets/Scripts/StandardSamples/SignInWithGoogle.meta
  Assets/Scripts/StandardSamples/SignInWithGoogle/SignInWithGoogleManager.cs
  Assets/Scripts/StandardSamples/SignInWithGoogle/SignInWithGoogleManager.cs.meta
  Assets/Scripts/StandardSamples/UI/Login/UILoginMenu.cs
  Assets/Scripts/StandardSamples/Utility/Extensions/ExternalCredentialTypeExtensions.cs
Labels: enhancement, tracked

#966 protected log config constructor
  com.playeveryware.eos/Runtime/Core/Config/LogLevelConfig.cs
Labels: tracked

#967 Deselect Field on Tab Change
  Assets/Plugins/Source/Editor/EditorWindows/EOSSettingsWindow.cs
  Assets/Plugins/Source/Editor/Utility/GUIEditorUtility.cs
Labels: UI, tracked

#971 Stop build pre/post-processor scripts from running if EOS_DISABLE is defined.
  Assets/Plugins/Source/Editor/Build/BuildRunner.cs
Labels: enhancement

#972 fix: Correct compile conditionals surrounding the writing of config v…
  com.playeveryware.eos/Runtime/Core/Config/Config.cs
  com.playeveryware.eos/Runtime/Core/Config/ProductConfig.cs
Labels: enhancement, fix, tracked

#974 fix: Correct compile conditionals surrounding the writing of config v…
  com.playeveryware.eos/Runtime/Core/Config/PlatformConfig.cs
Labels: fix, tracked

#946 Samples/button ux
  Assets/Prefab/playerDataStorageUI.prefab
  Assets/Prefab/titleStorageUI.prefab
  Assets/Scenes/StandardSamples/TitleStorage.unity
  Assets/Scripts/StandardSamples/UI/Common/SelectableStateHandler.cs
  Assets/Scripts/StandardSamples/UI/Common/SelectableStateHandler.cs.meta
  Assets/Scripts/StandardSamples/UI/Common/UITooltip.cs
  Assets/Scripts/StandardSamples/UI/Common/UITooltipManager.cs
  Assets/Scripts/StandardSamples/UI/Peer2Peer/UIConsoleInputField.cs
  Assets/Scripts/StandardSamples/UI/Storage/Player/UIPlayerDataStorageMenu.cs
  Assets/Scripts/StandardSamples/UI/Storage/Title/UITitleStorageMenu.cs
Labels: enhancement, UI, tracked

#965 Fix/deployment override
  com.playeveryware.eos/Runtime/Core/Config/EOSConfig.cs
Labels: fix, tracked

#979 Add missing `JsonConverter` attributes
  com.playeveryware.eos/Runtime/Core/Config/PlatformConfig.cs
Labels: enhancement, fix, tracked

#980 Fix `eos_package_description.json` file to leverage UPM layout
  etc/PackageConfigurations/eos_package_description.json
Labels: enhancement, fix, tracked

#982 fix(sample,oculus) : Move Oculus out of scope to disambiguate namespaces
  Assets/Scripts/StandardSamples/Oculus/OculusManager.cs
Labels: bug, tracked

#986 fix: `EOS_DISABLE`
  Assets/Plugins/Source/Editor/ConfigEditors/ConfigEditor.cs
  Assets/Plugins/Source/Editor/ConfigEditors/PlatformConfigEditor.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSPluginSettingsWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSUnitTestSettingsWindow.cs
  Assets/Plugins/Source/Editor/Platforms/Android/AndroidBuilder.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/WrappedInitializeThreadAffinity.cs
Labels: enhancement, tracked, release

#987 feat: Expand application of `ConfigFieldAttribute` usage
  Assets/Plugins/Android/Core/AndroidConfig.cs
  Assets/Plugins/Linux/Core/LinuxConfig.cs
  Assets/Plugins/Windows/Core/WindowsConfig.cs
  Assets/Plugins/iOS/Core/IOSConfig.cs
  Assets/Plugins/macOS/Core/MacOSConfig.cs
  com.playeveryware.eos/Runtime/Core/Config/ProductConfig.cs
Labels: documentation, enhancement, tracked, release

#988 fix: Reorg Extension Classes
  Assets/Plugins/Source/Editor/Utility/PackageFileUtility.cs
  Assets/Tests/PlayMode/Extensions/FileInfoExtensionsTests.cs
  Assets/Tests/PlayMode/Extensions/ListExtensionsTests.cs
  com.playeveryware.eos/Runtime/Core/Common/Extensions.meta
  com.playeveryware.eos/Runtime/Core/Common/Extensions/FileInfoExtensions.cs
  com.playeveryware.eos/Runtime/Core/Common/Extensions/FileInfoExtensions.cs.meta
  com.playeveryware.eos/Runtime/Core/Common/Extensions/ListExtensions.cs
  com.playeveryware.eos/Runtime/Core/Common/Extensions/ListExtensions.cs.meta
  com.playeveryware.eos/Runtime/Core/Common/Extensions/StringExtensions.cs
  com.playeveryware.eos/Runtime/Core/Common/Extensions/StringExtensions.cs.meta
  com.playeveryware.eos/Runtime/Core/Utility/FileSystemUtility.cs
Labels: enhancement, release
