Repository PlayEveryWare/eos_plugin_for_unity, pull requests merged in 2024-11, with the labels that each got.

#991 fix: In achievements sample, don't display the achievement icon until…
  Assets/Scripts/StandardSamples/UI/Achievements/UIAchievementsMenu.cs
Labels: UI, tracked

#990 doc(google,login) : google login doc
  com.playeveryware.eos/Documentation~/google_signin.md
Labels: documentation, tracked

#994 feat: Refactor Exigent NativeCode within `GfxPluginNativeRender`
  Assets/Plugins/Windows/x64/DynamicLibraryLoaderHelper-x64.dll
  Assets/Plugins/Windows/x64/GfxPluginNativeRender-x64.dll
  Assets/Plugins/Windows/x86/DynamicLibraryLoaderHelper-x86.dll
  Assets/Plugins/Windows/x86/GfxPluginNativeRender-x86.dll
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/NativeRender.vcxproj
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/NativeRender.vcxproj.filters
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/config.cpp
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/config.h
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/dllmain.cpp
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/eos_helpers.cpp
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/eos_helpers.h
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/eos_library_helpers.cpp
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/eos_library_helpers.h
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/framework.h
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/io_helpers.cpp
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/io_helpers.h
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/json_helpers.cpp
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/json_helpers.h
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/logging.cpp
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/logging.h
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/pch.h
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/string_helpers.cpp
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/string_helpers.h
Labels: documentation, enhancement, tracked, release

#997 fix: Sample Manager Menu Runs "ShowInternal" Only When It Should
  Assets/Scripts/P2PNetcodeSample/UI/P2PNetcode/UIP2PTransportMenu.cs
  Assets/Scripts/StandardSamples/UI/Common/SampleMenu.cs
  Assets/Scripts/StandardSamples/UI/CustomInvites/UICustomInvitesMenu.cs
  Assets/Scripts/StandardSamples/UI/Friends/UIFriendsMenu.cs
  Assets/Scripts/StandardSamples/UI/Leaderboard/UILeaderboardMenu.cs
  Assets/Scripts/StandardSamples/UI/Lobbies/UILobbiesMenu.cs
  Assets/Scripts/StandardSamples/UI/MatchMaking/UISessionsMatchmakingMenu.cs
  Assets/Scripts/StandardSamples/UI/Metrics/UIMetricsMenu.cs
  Assets/Scripts/StandardSamples/UI/Peer2Peer/HighFrequency/UIHighFrequencyPeer2PeerMenu.cs
  Assets/Scripts/StandardSamples/UI/Peer2Peer/UIPeer2PeerMenu.cs
  Assets/Scripts/StandardSamples/UI/PlayerReports/UIPlayerReportMenu.cs
  Assets/Scripts/StandardSamples/UI/Storage/Player/UIPlayerDataStorageMenu.cs
Labels: UI, tracked

#998 feat: Introduce native code console application
  Assets/Plugins/Windows/x64/.gitignore
  Assets/Plugins/Windows/x64/DynamicLibraryLoaderHelper-x64.dll
  Assets/Plugins/Windows/x64/GfxPluginNativeRender-x64.dll
  lib/NativeCode/DynamicLibraryLoaderHelper/.gitignore
  lib/NativeCode/DynamicLibraryLoaderHelper/ConsoleApplication/.gitignore
  lib/NativeCode/DynamicLibraryLoaderHelper/ConsoleApplication/ConsoleApplication.cpp
  lib/NativeCode/DynamicLibraryLoaderHelper/ConsoleApplication/ConsoleApplication.vcxproj
  lib/NativeCode/DynamicLibraryLoaderHelper/ConsoleApplication/ConsoleApplication.vcxproj.filters
  lib/NativeCode/DynamicLibraryLoaderHelper/Directory.Build.props
  lib/NativeCode/DynamicLibraryLoaderHelper/DynamicLibraryLoaderHelper.sln
  lib/NativeCode/DynamicLibraryLoaderHelper/DynamicLibraryLoaderHelper/DynamicLibraryLoaderHelper.vcxproj
  lib/NativeCode/DynamicLibraryLoaderHelper/DynamicLibraryLoaderHelper/DynamicLibraryLoaderHelper.vcxproj.filters
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/ConfigPaths.props
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/NativeRender.vcxproj
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/config.cpp
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/config.h
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/dllmain.cpp
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/eos_helpers.cpp
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/eos_helpers.h
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/eos_library_helpers.cpp
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/pch.h
Labels: enhancement, build, tracked

#999 feat: EOSManager can have UserLoginInfo Provided to it
  com.playeveryware.eos/Runtime/Core/EOSManager.cs
Labels: enhancement, tracked

#1000 feat: Introduce C# class library exposing `Config` related implementation.
  com.playeveryware.eos/Runtime/EOS_SDK/Core/Config.cs
  com.playeveryware.eos/Runtime/EOS_SDK/Core/Helper.cs
  lib/NativeCode/DynamicLibraryLoaderHelper/.gitignore
  lib/NativeCode/DynamicLibraryLoaderHelper/Directory.Build.props
  lib/NativeCode/DynamicLibraryLoaderHelper/DynamicLibraryLoaderHelper.sln
  lib/NativeCode/DynamicLibraryLoaderHelper/DynamicLibraryLoaderHelper/DynamicLibraryLoaderHelper.vcxproj
  lib/NativeCode/DynamicLibraryLoaderHelper/EOSPluginConfig/.gitignore
  lib/NativeCode/DynamicLibraryLoaderHelper/EOSPluginConfig/EOSPluginConfig.csproj
  lib/NativeCode/DynamicLibraryLoaderHelper/EOSPluginConfig/Properties/AssemblyInfo.cs
  lib/NativeCode/DynamicLibraryLoaderHelper/EOSPluginConfig/ResourceUtility.cs
  lib/NativeCode/DynamicLibraryLoaderHelper/EOSPluginConfig/com.playeveryware.eos/Runtime/Core/Application.cs
  lib/NativeCode/DynamicLibraryLoaderHelper/EOSPluginConfig/com.playeveryware.eos/Runtime/Core/Debug.cs
  lib/NativeCode/DynamicLibraryLoaderHelper/EOSPluginConfig/packages.config
Labels: enhancement, build, tracked

#1003 Use Func instead of Custom Delegate for GetUserLoginInfo
  com.playeveryware.eos/Runtime/Core/EOSManager.cs
Labels: enhancement, tracked

#1007 fix: Allow `ProductVersion` to be a string.
  com.playeveryware.eos/Runtime/Core/Config/ProductConfig.cs
Labels: enhancement, fix, tracked

#1005 fix: Use `PlatformConfig` and `ProductConfig` in place of `EOSConfig`
  Assets/Plugins/Source/Editor/Build/BuildRunner.cs
  Assets/Plugins/Source/Editor/Build/PlatformSpecificBuilder.cs
  Assets/Plugins/Source/Editor/Platforms/Android/AndroidBuilder.cs
  Assets/Plugins/Source/Editor/Platforms/Windows/WindowsBuilder.cs
  Assets/Plugins/Source/Editor/Utility/EACUtility.cs
  Assets/Plugins/Windows/Core/WindowsPlatformSpecifics.cs
  Assets/Scripts/StandardSamples/UI/Login/UILoginMenu.cs
  com.playeveryware.eos/Runtime/Core/Config/PlatformConfig.cs
  com.playeveryware.eos/Runtime/Core/EOSManager.cs
  com.playeveryware.eos/Runtime/Core/PlatformManager.cs
  com.playeveryware.eos/Runtime/Core/PlatformSpecifics.cs
  lib/NativeCode/DynamicLibraryLoaderHelper/EOSPluginConfig/EOSPluginConfig.csproj
Labels: enhancement, tracked

#1010 EOS Transport "clientId" => "transportId", associated comments
  Assets/Scripts/P2PNetcodeSample/Networking/EOSTransport.cs
Labels: documentation

#1016 fix: Correct IPMF Enum serialization
  Assets/StreamingAssets/EOS/eos_android_config.json
  Assets/StreamingAssets/EOS/eos_ios_config.json
  Assets/StreamingAssets/EOS/eos_linux_config.json
  Assets/StreamingAssets/EOS/eos_macos_config.json
  Assets/StreamingAssets/EOS/eos_windows_config.json
  Assets/Tests/PlayMode/Config/JsonConverters/ListOfStringsToEnumConverterTests.cs
  com.playeveryware.eos/Runtime/Core/Common/Utility/EnumUtility.cs
  com.playeveryware.eos/Runtime/Core/Config/JsonConverter/ListOfStringsToEnumConverters.cs
  com.playeveryware.eos/Runtime/Core/Config/PlatformConfig.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/Extensions/IntegratedPlatformManagementFlagsExtensions.cs
Labels: enhancement

#1024 fix: Add `EXTERNAL_TO_UNITY` compile conditionals
  com.playeveryware.eos/Runtime/Core/IPlatformSpecifics.cs
  com.playeveryware.eos/Runtime/Core/PlatformSpecifics.cs
Labels: enhancement
