Repository PlayEveryWare/eos_plugin_for_unity, pull requests merged in 2024-09, with the labels that each got.

#879 fix: Remove unreachable code
  com.playeveryware.eos/Runtime/Core/Config.cs
Labels: fix

#875 feat(lobby): Mute, deafen, without Lobby Members
  Assets/Prefab/lobbiesUI.prefab
  Assets/Scenes/StandardSamples/Lobbies.unity
  Assets/Scripts/EOSLobbyManager.cs
  Assets/Scripts/StandardSamples/UI/Lobbies/UILobbiesMenu.cs
Labels: enhancement

#881 fix: Corrected implementation of calling an asynchronous function from a synchronous context.
  com.playeveryware.eos/Runtime/Core/Config.cs
  com.playeveryware.eos/Runtime/Core/Utility/FileSystemUtility.cs
Labels: enhancement, fix, tracked

#851 Refactor Storage Managers in-situ
  Assets/Scripts/EOSPlayerDataStorageManager.cs
  Assets/Scripts/EOSTitleStorageManager.cs
  Assets/Scripts/EOSTransferInProgress.cs
  Assets/Scripts/StandardSamples/Services/DataService.cs
  Assets/Scripts/StandardSamples/Services/DataService.cs.meta
  Assets/Scripts/StandardSamples/Services/EOSService.cs
  Assets/Scripts/StandardSamples/UI/Storage/Player/UIPlayerDataStorageMenu.cs
  Assets/Scripts/StandardSamples/UI/Storage/Title/UITitleStorageMenu.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions.meta
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/EventHandlers.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/EventHandlers.cs.meta
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/Extensions.meta
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/Extensions/AuthScopeFlagsExtensions.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/Extensions/AuthScopeFlagsExtensions.cs.meta
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/Extensions/IntegratedPlatformManagementFlagsExtensions.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/Extensions/IntegratedPlatformManagementFlagsExtensions.cs.meta
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/Extensions/PlatformFlagsExtensions.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/Extensions/PlatformFlagsExtensions.cs.meta
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/FileRequestTransferWrapper.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/FileRequestTransferWrapper.cs.meta
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/IFileTransferRequest.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/IFileTransferRequest.cs.meta
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/PlayerDataStorageFileTransferRequestWrapper.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/PlayerDataStorageFileTransferRequestWrapper.cs.meta
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/TitleStorageFileTransferRequestWrapper.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/TitleStorageFileTransferRequestWrapper.cs.meta
Labels: enhancement

#883 (fix): Remove async file read logs
  com.playeveryware.eos/Runtime/Core/Utility/FileSystemUtility.cs
Labels: fix, tracked

#874 feat(lobby): Indicate lobby changed event kind
  Assets/Scripts/EOSEACLobbyManager.cs
  Assets/Scripts/EOSLobbyManager.cs
Labels: enhancement

#885 (fix): Remove unreferenced files
  com.playeveryware.eos/Runtime/Core/EnumeratorWrapper.cs
  com.playeveryware.eos/Runtime/Core/EnumeratorWrapper.cs.meta
Labels: enhancement, fix, tracked

#888 documentation: Document Friends Query Requiring Consent
  Assets/Scripts/StandardSamples/UI/Friends/UIFriendsMenu.cs
  com.playeveryware.eos/Documentation~/scene_walkthrough/P2P_netcode_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/P2P_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/auth&friends_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/customInvites_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/lobbies_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/player_reports_and_sanctions_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/sessions_and_matchmaking_walkthrough.md
  com.playeveryware.eos/Documentation~/uifriendsmenu.md
Labels: documentation, tracked

#887 fix: EOSManager to use print for all logs
  com.playeveryware.eos/Runtime/Core/EOSManager.cs
Labels: enhancement, tracked

#886 fix: EOSManager DontDestroyOnLoad, removal of EOSHostManager
  Assets/Prefab/Singletons.prefab
  Assets/Scripts/StandardSamples/Core.meta
  Assets/Scripts/StandardSamples/Core/EOSHostManager.cs
  Assets/Scripts/StandardSamples/Core/EOSHostManager.cs.meta
  Assets/Scripts/StandardSamples/Core/com.playeveryware.eos.samples.core.asmdef
  Assets/Scripts/StandardSamples/Core/com.playeveryware.eos.samples.core.asmdef.meta
  com.playeveryware.eos/Runtime/Core/EOSManager.cs
Labels: enhancement, tracked

#892 Break up `IPlatformSpecifics.cs` contents into individual files
  com.playeveryware.eos/Runtime/Core/EOSManagerPlatformSpecificsSingleton.cs
  com.playeveryware.eos/Runtime/Core/EOSManagerPlatformSpecificsSingleton.cs.meta
  com.playeveryware.eos/Runtime/Core/IEOSCoroutineOwner.cs
  com.playeveryware.eos/Runtime/Core/IEOSCoroutineOwner.cs.meta
  com.playeveryware.eos/Runtime/Core/IPlatformSpecifics.cs
Labels: enhancement, tracked

#895 fix: Relocate `ConfigFieldAttribute` and break into disparate components
  Assets/Plugins/Source/Editor/ConfigEditors/ConfigEditor.cs
  Assets/Plugins/Source/Editor/Configs/ConfigFieldAttribute.cs
  Assets/Plugins/Source/Editor/Utility/GUIEditorUtility.cs
  com.playeveryware.eos/Runtime/Core/Config.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes/ButtonFieldAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/ButtonFieldAttribute.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes/ConfigFieldAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/ConfigFieldAttribute.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes/ConfigFieldType.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/ConfigFieldType.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes/ConfigGroupAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/ConfigGroupAttribute.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes/DirectoryPathFieldAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/DirectoryPathFieldAttribute.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes/FilePathFieldAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/FilePathFieldAttribute.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/Config.cs
  com.playeveryware.eos/Runtime/Core/Config/Config.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/EOSConfig.cs
  com.playeveryware.eos/Runtime/Core/Config/EOSConfig.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/LogLevelConfig.cs
  com.playeveryware.eos/Runtime/Core/Config/LogLevelConfig.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/PlatformConfig.cs
  com.playeveryware.eos/Runtime/Core/Config/PlatformConfig.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/RuntimeConfig.cs
  com.playeveryware.eos/Runtime/Core/Config/RuntimeConfig.cs.meta
Labels: enhancement, tracked

#894 Simplifications to `ConfigEditor` implementations
  Assets/Plugins/Source/Editor/ConfigEditors/ConfigEditor.cs
  Assets/Plugins/Source/Editor/ConfigEditors/IConfigEditor.cs
  Assets/Plugins/Source/Editor/ConfigEditors/PlatformConfigEditor.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSEditorWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSPluginSettingsWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSSettingsWindow.cs
  Assets/Plugins/Source/Editor/Platforms/Android/AndroidConfigEditor.cs
  Assets/Plugins/Source/Editor/Platforms/Linux/LinuxConfigEditor.cs
  Assets/Plugins/Source/Editor/Platforms/iOS/IOSConfigEditor.cs
  Assets/Plugins/Source/Editor/Platforms/macOS/MacOSConfigEditor.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/ConfigGroupAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/PlatformConfig.cs
Labels: enhancement, tracked

#897 Change `FileSystemUtility.GetProjectPath()` to not use `Application.dataPath`
  com.playeveryware.eos/Runtime/Core/Utility/FileSystemUtility.cs
Labels: fix, tracked

#898 fix(config,IO) : Add missing if statement
  com.playeveryware.eos/Runtime/Core/Config/Config.cs
Labels: bug, fix, tracked

#906 Expansion of config attribute usage
  Assets/Plugins/Source/Editor/ConfigEditors/ConfigEditor.cs
  Assets/Plugins/Source/Editor/Utility/GUIEditorUtility.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/ConfigFieldAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/ConfigFieldType.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/ConfigGroupAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Config.cs
  com.playeveryware.eos/Runtime/Core/Config/EOSConfig.cs
  com.playeveryware.eos/Runtime/Core/Config/RuntimeConfig.cs
Labels: enhancement, tracked

#905 More Unit Tests
  Assets/Tests/PlayMode/Extensions/AuthScopeFlagsExtensionsTests.cs
  Assets/Tests/PlayMode/Extensions/CustomMappedEnumTestBase.cs
  Assets/Tests/PlayMode/Extensions/FileInfoExtensionsTests.cs
  Assets/Tests/PlayMode/Extensions/FileInfoExtensionsTests.cs.meta
  Assets/Tests/PlayMode/Extensions/IntegratedPlatformManagementFlagsExtensionsTests.cs
  Assets/Tests/PlayMode/Extensions/ListExtensionsTests.cs
  Assets/Tests/PlayMode/Extensions/ListExtensionsTests.cs.meta
  Assets/Tests/PlayMode/Extensions/PlatformFlagsExtensionsTests.cs
  Assets/Tests/PlayMode/LobbyTests.cs
  Assets/Tests/PlayMode/Utility/EnumUtilityTests.cs
  Assets/Tests/PlayMode/Utility/EnumUtilityTests.cs.meta
  ProjectSettings/Packages/com.unity.testtools.codecoverage/Settings.json
  com.playeveryware.eos/Runtime/Core/Extensions/ListExtensions.cs
  com.playeveryware.eos/Runtime/Core/Utility/EnumUtility.cs
  tools/coverage/historic/.gitignore
  tools/coverage/historic/Consolidated_CoverageHistory.xml
  tools/coverage/results/Report/badge_linecoverage.svg
  tools/coverage/results/current_coverage.txt
Labels: enhancement, tracked

#889 Add: login with the used option.
  Assets/Scenes/TestingAndValidationScenes/AuthenticationExpirationTest.unity
  Assets/Scripts/BuiltSceneTestScripts/AuthenticationExpirationTestManager.cs
  com.playeveryware.eos/Runtime/Core/EOSManager.cs
Labels: enhancement

#907 fix: Rename managers that have been refactored into services
  Assets/Scripts/EOSTransferInProgress.cs
  Assets/Scripts/StandardSamples/Services/EOSService.cs
  Assets/Scripts/StandardSamples/Services/PlayerDataStorageService.cs
  Assets/Scripts/StandardSamples/Services/PlayerDataStorageService.cs.meta
  Assets/Scripts/StandardSamples/Services/StorageService.cs
  Assets/Scripts/StandardSamples/Services/StorageService.cs.meta
  Assets/Scripts/StandardSamples/Services/TitleStorageService.cs
  Assets/Scripts/StandardSamples/Services/TitleStorageService.cs.meta
  Assets/Scripts/StandardSamples/UI/Storage/Player/UIPlayerDataStorageMenu.cs
  Assets/Scripts/StandardSamples/UI/Storage/Title/UITitleStorageMenu.cs
  Assets/Tests/PlayMode/PlayerDataStorageManagerTests.cs
Labels: enhancement

#910 fix: Correct version of Android Build Tools for Unity 2022.3 or newer.
  Assets/Plugins/Source/Editor/Platforms/Android/AndroidBuilder.cs
Labels: fix, tracked

#914 Unit Test Documentation
  com.playeveryware.eos/Documentation~/contributions.md
  com.playeveryware.eos/Documentation~/standards.md
  com.playeveryware.eos/Documentation~/unit_testing.md
Labels: documentation, enhancement, tracked, unit-testing

#915 Remove extra unreferenced files
  Assets/EOS/EOSManager.prefab
  Assets/EOS/EOSManager.prefab.meta
  Assets/Plugins/EOSManager.prefab
  Assets/Plugins/EOSManager.prefab.meta
  Assets/Prefab/P2P_Particle.prefab
  Assets/Prefab/P2P_Particle.prefab.meta
  Assets/Prefab/P2P_ParticleSystem.prefab
  Assets/Prefab/P2P_ParticleSystem.prefab.meta
  com.playeveryware.eos/Documentation~/configure_plugin.md
  docs/.editorconfig
Labels: documentation, enhancement, tracked

#912 Improve Unit Test Organization
  Assets/Tests/PlayMode/Config.meta
  Assets/Tests/PlayMode/Config/ConfigTests.cs
  Assets/Tests/PlayMode/Config/ConfigTests.cs.meta
  Assets/Tests/PlayMode/Services.meta
  Assets/Tests/PlayMode/Services/AchievementsTests.cs
  Assets/Tests/PlayMode/Services/AchievementsTests.cs.meta
  Assets/Tests/PlayMode/Services/ClientLobbyTests.cs
  Assets/Tests/PlayMode/Services/ClientLobbyTests.cs.meta
  Assets/Tests/PlayMode/Services/ClientSessionTests.cs
  Assets/Tests/PlayMode/Services/ClientSessionTests.cs.meta
  Assets/Tests/PlayMode/Services/EOSSessionsManagerTests.cs
  Assets/Tests/PlayMode/Services/EOSSessionsManagerTests.cs.meta
  Assets/Tests/PlayMode/Services/FriendsTests.cs
  Assets/Tests/PlayMode/Services/FriendsTests.cs.meta
  Assets/Tests/PlayMode/Services/LeaderboardTests.cs
  Assets/Tests/PlayMode/Services/LeaderboardTests.cs.meta
  Assets/Tests/PlayMode/Services/LobbyTests.cs
  Assets/Tests/PlayMode/Services/LobbyTests.cs.meta
  Assets/Tests/PlayMode/Services/PlayerDataStorageServiceTests.cs
  Assets/Tests/PlayMode/Services/PlayerDataStorageServiceTests.cs.meta
  Assets/Tests/PlayMode/Services/PlayerStorageTests.cs
  Assets/Tests/PlayMode/Services/PlayerStorageTests.cs.meta
  Assets/Tests/PlayMode/Services/SessionTests.cs
  Assets/Tests/PlayMode/Services/SessionTests.cs.meta
  Assets/Tests/PlayMode/Services/TitleStorageTests.cs
  Assets/Tests/PlayMode/Services/TitleStorageTests.cs.meta
Labels: tracked, unit-testing

#920 Relocate Docs
  .github/LICENSE.md
  .github/README.md
  CHANGELOG.md
Labels: documentation, enhancement, tracked

#921 Fix Documentation Links
  .github/README.md
  com.playeveryware.eos/Documentation~/android/README_Android.md
  com.playeveryware.eos/Documentation~/android/environment_setup_android.md
  com.playeveryware.eos/Documentation~/android/link_eos_library_settings.md
  com.playeveryware.eos/Documentation~/contributions.md
  com.playeveryware.eos/Documentation~/dev_env/HyperV_Linux_Guest_VM.md
  com.playeveryware.eos/Documentation~/dev_env/Ubuntu_Development_Environment.md
  com.playeveryware.eos/Documentation~/docs_on_docs/doc_style_guide.md
  com.playeveryware.eos/Documentation~/frequently_asked_questions.md
  com.playeveryware.eos/Documentation~/iOS/README_iOS.md
  com.playeveryware.eos/Documentation~/images/hyperv_linux_guest_vm/ubuntu-18.04-LTS.png
  com.playeveryware.eos/Documentation~/macOS/README_macOS.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/P2P_netcode_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/P2P_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/achievements_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/auth&friends_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/customInvites_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/leaderboards_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/lobbies_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/metrics_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/performance_stress_test_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/player_data_storage_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/player_reports_and_sanctions_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/sessions_and_matchmaking_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/store_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/title_storage_walkthrough.md
  com.playeveryware.eos/Documentation~/standards.md
  com.playeveryware.eos/README.md
Labels: documentation, enhancement, tracked

#924 Fix Documentation Links
  com.playeveryware.eos/Documentation~/Walkthrough.md
  com.playeveryware.eos/Documentation~/add_plugin.md
  com.playeveryware.eos/Documentation~/android/README_Android.md
  com.playeveryware.eos/Documentation~/android/environment_setup_android.md
  com.playeveryware.eos/Documentation~/android/link_eos_library_settings.md
  com.playeveryware.eos/Documentation~/apple_signin.md
  com.playeveryware.eos/Documentation~/class_description.md
  com.playeveryware.eos/Documentation~/configure_plugin.md
  com.playeveryware.eos/Documentation~/contributions.md
  com.playeveryware.eos/Documentation~/creating_the_upm_package.md
  com.playeveryware.eos/Documentation~/dev_env/HyperV_Linux_Guest_VM.md
  com.playeveryware.eos/Documentation~/dev_env/Ubuntu_Development_Environment.md
  com.playeveryware.eos/Documentation~/disable_plugin_per_platform.md
  com.playeveryware.eos/Documentation~/docs_on_docs/doc_style_guide.md
  com.playeveryware.eos/Documentation~/dotnet_quirks.md
  com.playeveryware.eos/Documentation~/easy_anticheat_configuration.md
  com.playeveryware.eos/Documentation~/ecom.md
  com.playeveryware.eos/Documentation~/enabling_voice.md
  com.playeveryware.eos/Documentation~/eos_config_security.md
  com.playeveryware.eos/Documentation~/eos_features.md
  com.playeveryware.eos/Documentation~/epic_game_store.md
  com.playeveryware.eos/Documentation~/frequently_asked_questions.md
  com.playeveryware.eos/Documentation~/generating_docfx_static_site.md
  com.playeveryware.eos/Documentation~/iOS/README_iOS.md
  com.playeveryware.eos/Documentation~/login_type_by_platform.md
  com.playeveryware.eos/Documentation~/macOS/README_macOS.md
  com.playeveryware.eos/Documentation~/overlay.md
  com.playeveryware.eos/Documentation~/player_authentication.md
  com.playeveryware.eos/Documentation~/plugin_advantages.md
  com.playeveryware.eos/Documentation~/samples.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/P2P_netcode_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/P2P_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/achievements_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/auth&friends_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/customInvites_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/leaderboards_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/lobbies_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/metrics_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/performance_stress_test_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/player_data_storage_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/player_reports_and_sanctions_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/sessions_and_matchmaking_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/store_walkthrough.md
  com.playeveryware.eos/Documentation~/scene_walkthrough/title_storage_walkthrough.md
  com.playeveryware.eos/Documentation~/standards.md
  com.playeveryware.eos/Documentation~/steam.md
  com.playeveryware.eos/Documentation~/supported_platforms.md
  com.playeveryware.eos/Documentation~/supported_versions_of_unity.md
  com.playeveryware.eos/Documentation~/uifriendsmenu.md
  com.playeveryware.eos/Documentation~/unity_specific.md
  com.playeveryware.eos/Documentation~/upgrading_to_new_versions_of_eos.md
  com.playeveryware.eos/README.md
Labels: documentation, enhancement, tracked

#913 feat(config): Customizable Overlay Config Button Combination
  Assets/Plugins/Source/Editor/EditorWindows/EOSSettingsWindow.cs
  Assets/Plugins/Source/Editor/Utility/GUIEditorUtility.cs
  com.playeveryware.eos/Runtime/Core/Config/EOSConfig.cs
  com.playeveryware.eos/Runtime/Core/EOSManager.cs
Labels: enhancement

#922 Documentation Link Checker
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/check-markdown-links.yml
  tools/scripts/check_links.py
Labels: documentation, enhancement, build

#926 `CHANGELOG.md` scripting assistant
  tools/scripts/print-commits.sh
Labels: enhancement, build, tracked

#928 Release `v3.3.3`
  .github/workflows/check-for-package-difference.yml
  Assets/Plugins/Source/Editor/Configs/UnitTestConfig.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSSettingsWindow.cs
  Assets/Plugins/Windows/x64/DynamicLibraryLoaderHelper-x64.dll
  Assets/Plugins/Windows/x64/GfxPluginNativeRender-x64.dll
  Assets/Plugins/Windows/x86/DynamicLibraryLoaderHelper-x86.dll
  Assets/Plugins/Windows/x86/GfxPluginNativeRender-x86.dll
  com.playeveryware.eos/CHANGELOG.md
  com.playeveryware.eos/Runtime/Core/Config/EOSConfig.cs
  com.playeveryware.eos/Runtime/Core/EOSPackageInfo.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/EventHandlers.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/FileRequestTransferWrapper.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/IFileTransferRequest.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/PlayerDataStorageFileTransferRequestWrapper.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/TitleStorageFileTransferRequestWrapper.cs
  com.playeveryware.eos/Runtime/Core/Utility/FileSystemUtility.cs
  com.playeveryware.eos/package.json
  etc/PackageConfigurations/eos_package_description.json
Labels: enhancement, tracked

#930 Make test classes `partial` so they can be expanded
  Assets/Tests/Common/EOSTestBase.cs
  Assets/Tests/PlayMode/AuthenticationTests.cs
  Assets/Tests/PlayMode/ConnectTests.cs
  Assets/Tests/PlayMode/Services/AchievementsTests.cs
  Assets/Tests/PlayMode/Services/ClientLobbyTests.cs
  Assets/Tests/PlayMode/Services/ClientSessionTests.cs
  Assets/Tests/PlayMode/Services/EOSSessionsManagerTests.cs
  Assets/Tests/PlayMode/Services/FriendsTests.cs
  Assets/Tests/PlayMode/Services/LeaderboardTests.cs
  Assets/Tests/PlayMode/Services/LobbyTests.cs
  Assets/Tests/PlayMode/Services/PlayerDataStorageServiceTests.cs
  Assets/Tests/PlayMode/Services/PlayerStorageTests.cs
  Assets/Tests/PlayMode/Services/SessionTests.cs
  Assets/Tests/PlayMode/Services/TitleStorageTests.cs
Labels: enhancement, fix, tracked

#932 Swap `UnityEngine.JsonUtility` for `Newtonsoft.Json`
  Packages/packages-lock.json
  com.playeveryware.eos/Runtime/Core/Utility/JsonUtility.cs
  com.playeveryware.eos/package.json
Labels: enhancement, tracked

#934 fix: Remove mentions of the hackForceSendInputDirectlyToSDK
  Assets/StreamingAssets/EOS/EpicOnlineServicesConfig.json
  Assets/StreamingAssets/EOS/eos_android_config.json
  Assets/StreamingAssets/EOS/eos_ios_config.json
  Assets/StreamingAssets/EOS/eos_linux_config.json
  Assets/StreamingAssets/EOS/eos_macos_config.json
  com.playeveryware.eos/Runtime/Core/Config/EOSConfig.cs
Labels: tracked, plugin_issue

#936 More inviting supported versions
  com.playeveryware.eos/Documentation~/supported_versions_of_unity.md
Labels: documentation, tracked

#923 Walkthrough
  com.playeveryware.eos/Documentation~/configure_plugin.md
  com.playeveryware.eos/Documentation~/getting_started_guide/README.md
  com.playeveryware.eos/Documentation~/getting_started_guide/epic_developerportal_productlanding.png
  com.playeveryware.eos/Documentation~/getting_started_guide/epic_developerportal_signin_or_createaccount.png
  com.playeveryware.eos/Documentation~/getting_started_guide/plugin_eosconfiguration.png
Labels: documentation, tracked

#938 Config Field Members Type Update
  Assets/Plugins/Source/Editor/ConfigEditors/PlatformConfigEditor.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSSettingsWindow.cs
  Assets/Plugins/Source/Editor/Platforms/Windows/WindowsBuilder.cs
  Assets/Plugins/Source/Editor/Utility/GUIEditorUtility.cs
  Assets/Plugins/Windows/x64/GfxPluginNativeRender-x64.dll
  Assets/Plugins/Windows/x86/GfxPluginNativeRender-x86.dll
  Assets/StreamingAssets/EOS/EpicOnlineServicesConfig.json
  Assets/StreamingAssets/EOS/eos_android_config.json
  Assets/StreamingAssets/EOS/eos_ios_config.json
  Assets/StreamingAssets/EOS/eos_linux_config.json
  Assets/Tests/PlayMode/Config/JsonConverters.meta
  Assets/Tests/PlayMode/Config/JsonConverters/ListOfStringsToEnumConverterTests.cs
  Assets/Tests/PlayMode/Config/JsonConverters/ListOfStringsToEnumConverterTests.cs.meta
  Assets/Tests/PlayMode/Config/JsonConverters/StringToTypeConverterTests.cs
  Assets/Tests/PlayMode/Config/JsonConverters/StringToTypeConverterTests.cs.meta
  Assets/Tests/PlayMode/com.playeveryware.eos.tests.playmode.asmdef
  com.playeveryware.eos/Runtime/Core/Config/Attributes/ConfigFieldType.cs
  com.playeveryware.eos/Runtime/Core/Config/Config.cs
  com.playeveryware.eos/Runtime/Core/Config/EOSConfig.cs
  com.playeveryware.eos/Runtime/Core/Config/JsonConverter.meta
  com.playeveryware.eos/Runtime/Core/Config/JsonConverter/ListOfStringsToEnumConverters.cs
  com.playeveryware.eos/Runtime/Core/Config/JsonConverter/ListOfStringsToEnumConverters.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/JsonConverter/StringToTypeConverter.cs
  com.playeveryware.eos/Runtime/Core/Config/JsonConverter/StringToTypeConverter.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/PlatformConfig.cs
  com.playeveryware.eos/Runtime/Core/EOSManager.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/Extensions/PlatformFlagsExtensions.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/WrappedPlatformFlags.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/WrappedPlatformFlags.cs.meta
  com.playeveryware.eos/Runtime/Core/Utility/JsonUtility.cs
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/dllmain.cpp
Labels: enhancement, tracked, plugin_issue, unit-testing
