Repository PlayEveryWare/eos_plugin_for_unity, pull requests merged in 2024-12, with the labels that each got.

#1034 fix: Disable Application Focus Logging by Default
  com.playeveryware.eos/Runtime/Core/EOSManager.cs
Labels: enhancement

#1029 feat: `ConfigurationUtility`
  Assets/Plugins/Windows/Core/WindowsPlatformSpecifics.cs
  com.playeveryware.eos/Runtime/Core/EOSManager.cs
  com.playeveryware.eos/Runtime/Core/IPlatformSpecifics.cs
  com.playeveryware.eos/Runtime/Core/PlatformSpecifics.cs
  com.playeveryware.eos/Runtime/Core/Utility/ConfigurationUtility.cs
  com.playeveryware.eos/Runtime/Core/Utility/ConfigurationUtility.cs.meta
Labels: enhancement, tracked

#1030 chore: (Re)introduce `ManagedPluginCode` project.
  Assets/Plugins/Windows/Core/WindowsPlatformSpecifics.cs
  com.playeveryware.eos/Runtime/Core/Config/Config.cs
  com.playeveryware.eos/Runtime/Core/Config/EOSConfig.cs
  lib/NativeCode/DynamicLibraryLoaderHelper/DynamicLibraryLoaderHelper.sln
  lib/NativeCode/DynamicLibraryLoaderHelper/ManagedPluginCode/.gitignore
  lib/NativeCode/DynamicLibraryLoaderHelper/ManagedPluginCode/Application.cs
  lib/NativeCode/DynamicLibraryLoaderHelper/ManagedPluginCode/Debug.cs
  lib/NativeCode/DynamicLibraryLoaderHelper/ManagedPluginCode/ManagedPluginCode.csproj
  lib/NativeCode/DynamicLibraryLoaderHelper/ManagedPluginCode/Properties/AssemblyInfo.cs
  lib/NativeCode/DynamicLibraryLoaderHelper/ManagedPluginCode/packages.config
Labels: enhancement, tracked

#1040 chore: Renaming "print" to "log" where applicable
  Assets/Plugins/Android/Core/AndroidPlatformSpecifics.cs
  Assets/Plugins/Source/Editor/Build/BuildPackage.cs
  Assets/Scripts/P2PNetcodeSample/Networking/EOSTransport.cs
  Assets/Scripts/P2PNetcodeSample/Networking/EOSTransportManager.cs
  com.playeveryware.eos/Runtime/Core/DLLHandle.cs
  com.playeveryware.eos/Runtime/Core/EOSManager.cs
  com.playeveryware.eos/Runtime/Core/EOSManager_DynamicLoading.cs
Labels: tracked

#1045 feat: Notify user that Ecommerce won't work in the Editor
  Assets/Prefab/storeUI.prefab
  Assets/Scripts/StandardSamples/UI/Common/DisabledInEditorWarningPanel.cs
  Assets/Scripts/StandardSamples/UI/Common/DisabledInEditorWarningPanel.cs.meta
Labels: tracked

#1043 fix: `UIDebugLog` enforces the maximum length of a log
  Assets/Scripts/StandardSamples/UI/Common/UIDebugLog.cs
Labels: tracked

#1050 feat: Upgrade Platform Toolset and VS Versions
  com.playeveryware.eos/Documentation~/contributions.md
  lib/NativeCode/DynamicLibraryLoaderHelper/DynamicLibraryLoaderHelper/DynamicLibraryLoaderHelper.vcxproj
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/NativeRender.vcxproj
Labels: enhancement

#1055 chore: Merge `stable` into `development` to resolve divergent histories
  Assets/Plugins/Android/Core/AndroidFileIOHelper.cs
  Assets/Plugins/Source/Editor/Platforms/iOS/IOSBuilder.cs
  com.playeveryware.eos/CHANGELOG.md
  com.playeveryware.eos/Runtime/Core/Config/Config.cs
  com.playeveryware.eos/Runtime/Core/EOSPackageInfo.cs
  com.playeveryware.eos/Runtime/Core/Utility/FileSystemUtility.cs
  com.playeveryware.eos/Runtime/Core/Utility/LogLevelUtility.cs
  com.playeveryware.eos/package.json
Labels: fix

#1053 Merge Release `3.3.4` into `development`
  Assets/Plugins/Source/Editor/Platforms/iOS/IOSBuilder.cs
  Assets/Plugins/Windows/Core/WindowsPlatformSpecifics.cs
  Assets/Plugins/Windows/x64/GfxPluginNativeRender-x64.dll
  Assets/Plugins/Windows/x86/GfxPluginNativeRender-x86.dll
  Assets/StreamingAssets/EOS/EpicOnlineServicesConfig.json
  Assets/StreamingAssets/EOS/eos_android_config.json
  Assets/StreamingAssets/EOS/eos_ios_config.json
  Assets/StreamingAssets/EOS/eos_linux_config.json
Labels: enhancement, release

#1052 fix: Restore functionality of the `EOS_DISABLE` scripting define.
  Assets/Plugins/Android/Core/AndroidConfig.cs
  Assets/Plugins/Linux/Core/LinuxConfig.cs
  Assets/Plugins/Source/Editor/Build/BuildPackage.cs
  Assets/Plugins/Source/Editor/Build/BuildRunner.cs
  Assets/Plugins/Source/Editor/Build/PlatformSpecificBuilder.cs
  Assets/Plugins/Source/Editor/ConfigEditors/ConfigEditor.cs
  Assets/Plugins/Source/Editor/ConfigEditors/PlatformConfigEditor.cs
  Assets/Plugins/Source/Editor/Configs/AndroidBuildConfig.cs
  Assets/Plugins/Source/Editor/Configs/EditorConfig.cs
  Assets/Plugins/Source/Editor/Configs/LibraryBuildConfig.cs
  Assets/Plugins/Source/Editor/Configs/PackagingConfig.cs
  Assets/Plugins/Source/Editor/Configs/PrebuildConfig.cs
  Assets/Plugins/Source/Editor/Configs/SigningConfig.cs
  Assets/Plugins/Source/Editor/Configs/SteamConfig.cs
  Assets/Plugins/Source/Editor/Configs/ToolsConfig.cs
  Assets/Plugins/Source/Editor/Configs/UnitTestConfig.cs
  Assets/Plugins/Source/Editor/EditorWindows/CreatePackageWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSSettingsWindow_DEPRECATED.cs
  Assets/Plugins/Source/Editor/EditorWindows/InstallEOSZipWindow.cs
  Assets/Plugins/Source/Editor/Platforms/Linux/LinuxBuilder.cs
  Assets/Plugins/Source/Editor/Platforms/Windows/WindowsBuilder.cs
  Assets/Plugins/Source/Editor/Platforms/macOS/MacOSBuilder.cs
  Assets/Plugins/Source/Editor/Utility/BuildUtility.cs
  Assets/Plugins/Source/Editor/Utility/EACUtility.cs
  Assets/Plugins/Source/Editor/Utility/GUIEditorUtility.cs
  Assets/Plugins/Source/Editor/Utility/MakefileUtility.cs
  Assets/Plugins/Source/Editor/Utility/SigningUtility.cs
  Assets/Plugins/Source/Editor/Utility/UnityPackageCreationUtility.cs
  Assets/Plugins/Windows/Core/WindowsConfig.cs
  Assets/Plugins/iOS/Core/IOSConfig.cs
  Assets/Plugins/macOS/Core/MacOSConfig.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/ButtonFieldAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/ConfigFieldAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/DirectoryPathFieldAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/FilePathFieldAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/PlatformDependentConfigFieldAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Config.cs
  com.playeveryware.eos/Runtime/Core/Config/EOSConfig.cs
  com.playeveryware.eos/Runtime/Core/Config/LogLevelConfig.cs
  com.playeveryware.eos/Runtime/Core/Config/PlatformConfig.cs
  com.playeveryware.eos/Runtime/Core/Config/ProductConfig.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/WrappedPlatformFlags.cs
  com.playeveryware.eos/Runtime/Core/PlatformManager.cs
  com.playeveryware.eos/Runtime/Core/Utility/ConfigurationUtility.cs
Labels: fix

#1057 fix: Correct error introduced from merge
  com.playeveryware.eos/Runtime/Core/Utility/FileSystemUtility.cs
Labels: fix

#1056 docs: Updating upgrading_to_new_versions_of_eos.md
  com.playeveryware.eos/Documentation~/upgrading_to_new_versions_of_eos.md
Labels: documentation, tracked

#1060 fix: Upgrade Visual Studio version to 2022.
  lib/NativeCode/DynamicLibraryLoaderHelper/DynamicLibraryLoaderHelper.sln
Labels: enhancement, fix

#1066 fix: If `definition.StatThersholds` is null, don't iterate on it for selectedDescription
  Assets/Scripts/StandardSamples/UI/Achievements/UIAchievementsMenu.cs
Labels: tracked
