Repository PlayEveryWare/eos_plugin_for_unity, pull requests merged in 2024-08, with the labels that each got.

#822 `SteamConfig` relocation (from both a code and UI organization perspective)
  Assets/Plugins/Source/Editor/Build/BuildRunner.cs
  Assets/Plugins/Source/Editor/ConfigEditors/ConfigEditor.cs
  Assets/Plugins/Source/Editor/ConfigEditors/IConfigEditor.cs
  Assets/Plugins/Source/Editor/Configs/ConfigFieldAttribute.cs
  Assets/Plugins/Source/Editor/Configs/SteamConfig.cs
  Assets/Plugins/Source/Editor/Configs/SteamConfig.cs.meta
  Assets/Plugins/Source/Editor/EditorWindows/EOSPluginSettingsWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSSettingsWindow.cs
  Assets/Plugins/Source/Editor/Utility/GUIEditorUtility.cs
  Assets/Plugins/Source/Editor/Utility/Steam/SteamworksUtility.cs
  Assets/Plugins/Source/Editor/Utility/Steam/SteamworksUtility.cs.meta
Labels: enhancement

#829 Fix warnings when Steamworks.NET is not setup
  Assets/Scripts/StandardSamples/Steam/SteamManager.cs
Labels: fix

#828 fix: Correct file path in `eos_package_description.json` file.
  etc/PackageConfigurations/eos_package_description.json
Labels: fix

#826 Make `EOSSettingsWindow` aware of available build targets
  Assets/Plugins/Source/Editor/ConfigEditors/IPlatformConfigEditor.cs
  Assets/Plugins/Source/Editor/ConfigEditors/IPlatformConfigEditor.cs.meta
  Assets/Plugins/Source/Editor/ConfigEditors/PlatformConfigEditor.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSSettingsWindow.cs
  com.playeveryware.eos/Runtime/Core/PlatformManager.cs
Labels: enhancement

#835 Change `EOSManager` to use events instead of lists of delegate instances.
  com.playeveryware.eos/Runtime/Core/EOSManager.cs
Labels: enhancement

#834 `SampleMenu` & `EOSService`
  Assets/Prefab/achievementsUI.prefab
  Assets/Scenes/P2PNetcodeSample/P2PNetcode.unity
  Assets/Scenes/StandardSamples/Achievements.unity
  Assets/Scenes/StandardSamples/AuthAndFriends.unity
  Assets/Scenes/StandardSamples/CustomInvites.unity
  Assets/Scenes/StandardSamples/HighFrequencyP2P.unity
  Assets/Scenes/StandardSamples/Leaderboards.unity
  Assets/Scenes/StandardSamples/Lobbies.unity
  Assets/Scenes/StandardSamples/Peer2Peer.unity
  Assets/Scenes/StandardSamples/PlayerDataStorage.unity
  Assets/Scenes/StandardSamples/PlayerReportsAndSanctions.unity
  Assets/Scenes/StandardSamples/SessionsAndMatchmaking.unity
  Assets/Scenes/StandardSamples/Store.unity
  Assets/Scenes/StandardSamples/TitleStorage.unity
  Assets/Scripts/P2PNetcodeSample/UI/P2PNetcode/UIP2PTransportMenu.cs
  Assets/Scripts/StandardSamples/Services/AchievementsService.cs
  Assets/Scripts/StandardSamples/Services/AchievementsService.cs.meta
  Assets/Scripts/StandardSamples/Services/EOSService.cs
  Assets/Scripts/StandardSamples/Services/StatsService.cs
  Assets/Scripts/StandardSamples/UI/Achievements/UIAchievementButton.cs
  Assets/Scripts/StandardSamples/UI/Achievements/UIAchievementsMenu.cs
  Assets/Scripts/StandardSamples/UI/Common/SampleMenu.cs
  Assets/Scripts/StandardSamples/UI/Common/SampleMenu.cs.meta
  Assets/Scripts/StandardSamples/UI/Common/UIISampleScene.cs
  Assets/Scripts/StandardSamples/UI/Common/UISampleSceneUIContainer.cs
  Assets/Scripts/StandardSamples/UI/CustomInvites/UICustomInvitesMenu.cs
  Assets/Scripts/StandardSamples/UI/Friends/UIFriendInteractionSource.cs
  Assets/Scripts/StandardSamples/UI/Friends/UIFriendsMenu.cs
  Assets/Scripts/StandardSamples/UI/Leaderboard/UILeaderboardMenu.cs
  Assets/Scripts/StandardSamples/UI/Lobbies/UILobbiesMenu.cs
  Assets/Scripts/StandardSamples/UI/MatchMaking/UISessionsMatchmakingMenu.cs
  Assets/Scripts/StandardSamples/UI/Metrics/UIMetricsMenu.cs
  Assets/Scripts/StandardSamples/UI/Peer2Peer/HighFrequency/UIHighFrequencyPeer2PeerMenu.cs
  Assets/Scripts/StandardSamples/UI/Peer2Peer/UIPeer2PeerMenu.cs
  Assets/Scripts/StandardSamples/UI/PlayerReports/UIPlayerReportMenu.cs
  Assets/Scripts/StandardSamples/UI/Storage/Player/UIPlayerDataStorageMenu.cs
  Assets/Scripts/StandardSamples/UI/Storage/Title/UITitleStorageMenu.cs
  Assets/Scripts/StandardSamples/UI/Store/UIStoreMenu.cs
  com.playeveryware.eos/Runtime/Core/AuthenticationListener.cs
  com.playeveryware.eos/Runtime/Core/AuthenticationListener.cs.meta
  com.playeveryware.eos/Runtime/Core/EOSManager.cs
Labels: enhancement

#858 Fix to package description
  etc/PackageConfigurations/eos_package_description.json
Labels: fix

#846 Better data handling in file transfers
  Assets/Scripts/EOSPlayerDataStorageManager.cs
  Assets/Scripts/EOSTitleStorageManager.cs
  Assets/Scripts/EOSTransferInProgress.cs
Labels: fix

#849 Fix Unit Test Settings Window
  Assets/Plugins/Source/Editor/ConfigEditors/ConfigEditor.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSUnitTestSettingsWindow.cs
Labels: fix

#841 fix(eosmanager): Manage application shutdown only on Application.quitting
  com.playeveryware.eos/Runtime/Core/EOSManager.cs
Labels: plugin_issue

#857 Add author details to `package.json` file.
  com.playeveryware.eos/package.json
Labels: documentation, enhancement

#854 Service Disposal Pattern
  Assets/Scripts/StandardSamples/Services/AchievementsService.cs
  Assets/Scripts/StandardSamples/Services/EOSService.cs
  Assets/Scripts/StandardSamples/Services/StatsService.cs
Labels: enhancement

#869 Fixes for unit test
  Assets/Tests/PlayMode/AchievementsTests.cs
  Assets/Tests/PlayMode/LeaderboardTests.cs
Labels: bug, tracked

#865 Unit Test Code Coverage Measurement Tools
  Assets/Tests/Common/CodeCoverageHistoryCleaner.cs
  Assets/Tests/Common/CodeCoverageHistoryCleaner.cs.meta
  Assets/Tests/Common/TestListener.cs
  Assets/Tests/Common/TestListener.cs.meta
  Assets/Tests/Common/com.playeveryware.eos.tests.common.asmdef
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/Packages/com.unity.testtools.codecoverage/Settings.json
  README.md
  com.playeveryware.eos/README.md
  tools/coverage/historic/.gitignore
  tools/coverage/historic/Consolidated_CoverageHistory.xml
  tools/coverage/results/.gitignore
  tools/coverage/results/Report/badge_linecoverage.svg
  tools/coverage/results/current_coverage.txt
Labels: enhancement, tracked

#868 Release-3.3.2 merge
  com.playeveryware.eos/CHANGELOG.md
  com.playeveryware.eos/Runtime/Core/EOSManager.cs
  com.playeveryware.eos/Runtime/Core/Utility/LogLevelUtility.cs
  com.playeveryware.eos/package.json
Labels: tracked, release

#870 fix: Remove field member defined inside `StatsService` that was assigned a value but never used.
  Assets/Scripts/StandardSamples/Services/StatsService.cs
Labels: fix, tracked

#876 fix: EOS Disable in AuthenticationListener
  com.playeveryware.eos/Runtime/Core/AuthenticationListener.cs
Labels: fix, tracked

#872 Add "BlockParticipant" feature to `EOSLobbyManager.cs`
  Assets/Scripts/EOSLobbyManager.cs
Labels: enhancement
