Repository PlayEveryWare/eos_plugin_for_unity, pull requests merged in 2024-07, with the labels that each got.

#754 Make use of `async` keyword conditional on whether SteamWorks is enabled or not.
  Assets/Scripts/Steam/SteamManager.cs
Labels: fix

#759 chore: Add MIT license badge to README.md file.
  README.md
  etc/PackageTemplate/README.md
Labels: documentation, enhancement

#760 chore: Move new `LogLevelWindow` into `EditorWindows` subdirectory.
  Assets/Plugins/Source/Editor/EditorWindows/LogLevelWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/LogLevelWindow.cs.meta
Labels: enhancement, fix

#762 Release `v3.3.0`
  Assets/Plugins/Linux/libDynamicLibraryLoaderHelper.so
  Assets/Plugins/Linux/libDynamicLibraryLoaderHelper.so.meta
  Assets/Plugins/Windows/x64/DynamicLibraryLoaderHelper-x64.dll
  Assets/Plugins/Windows/x64/GfxPluginNativeRender-x64.dll
  Assets/Plugins/Windows/x86/DynamicLibraryLoaderHelper-x86.dll
  Assets/Plugins/Windows/x86/GfxPluginNativeRender-x86.dll
  CHANGELOG.md
  etc/PackageTemplate/CHANGELOG.md
  etc/PackageTemplate/package.json
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/dllmain.cpp
  lib/NativeCode/DynamicLibraryLoaderHelper_Linux/DynamicLibraryLoaderHelper_Linux.cpp
  lib/NativeCode/DynamicLibraryLoaderHelper_Linux/Makefile
  lib/NativeCode/DynamicLibraryLoaderHelper_Linux/Memory_Linux.cpp
  lib/NativeCode/DynamicLibraryLoaderHelper_macOS/DynamicLibraryLoaderHelper_macos.cpp
  lib/NativeCode/DynamicLibraryLoaderHelper_macOS/Makefile
  lib/NativeCode/DynamicLibraryLoaderHelper_macOS/Memory_macOS.cpp
  lib/NativeCode/include/windows/framework.h
  lib/NativeCode/src/DynamicLibraryLoaderHelper.cpp
  lib/NativeCode/src/Memory.cpp
  lib/NativeCode/src/windows/DynamicLibraryLoaderHelper_Win32.cpp
Labels: enhancement

#774 fix(log,config) : fix renamed/capitalized config entries
  Assets/StreamingAssets/EOS/log_level_config.json
Labels: fix

#773 docs: update the doc with some things that were missing
  docs/standards.md
Labels: documentation

#777 refactor: remove `LoadDelegatesWithReflection` and `LoadDelegatesByHand`
  Assets/Plugins/Source/Core/EOSManager_DynamicLoading.cs
Labels: enhancement

#775 Editor UI Improvements
  Assets/Plugins/Source/Editor/ConfigEditors/AndroidBuildConfigEditor.cs
  Assets/Plugins/Source/Editor/ConfigEditors/AndroidBuildConfigEditor.cs.meta
  Assets/Plugins/Source/Editor/ConfigEditors/ConfigEditor.cs
  Assets/Plugins/Source/Editor/ConfigEditors/IConfigEditor.cs
  Assets/Plugins/Source/Editor/ConfigEditors/LibraryBuildConfigEditor.cs
  Assets/Plugins/Source/Editor/ConfigEditors/LibraryBuildConfigEditor.cs.meta
  Assets/Plugins/Source/Editor/ConfigEditors/PackagingConfigEditor.cs
  Assets/Plugins/Source/Editor/ConfigEditors/PackagingConfigEditor.cs.meta
  Assets/Plugins/Source/Editor/ConfigEditors/PrebuildConfigEditor.cs
  Assets/Plugins/Source/Editor/ConfigEditors/PrebuildConfigEditor.cs.meta
  Assets/Plugins/Source/Editor/ConfigEditors/ToolsConfigEditor.cs
  Assets/Plugins/Source/Editor/Configs/AndroidBuildConfig.cs
  Assets/Plugins/Source/Editor/Configs/ConfigFieldAttribute.cs
  Assets/Plugins/Source/Editor/Configs/ConfigFieldAttribute.cs.meta
  Assets/Plugins/Source/Editor/Configs/EditorConfig.cs
  Assets/Plugins/Source/Editor/Configs/LibraryBuildConfig.cs
  Assets/Plugins/Source/Editor/Configs/PackagingConfig.cs
  Assets/Plugins/Source/Editor/Configs/PrebuildConfig.cs
  Assets/Plugins/Source/Editor/Configs/SigningConfig.cs
  Assets/Plugins/Source/Editor/Configs/ToolsConfig.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSPluginSettingsWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSSettingsWindow.cs
  Assets/Plugins/Source/Editor/Utility/GUIEditorUtility.cs
  Assets/Plugins/Source/Editor/Utility/SigningUtility.cs
  Assets/Plugins/Source/Editor/Utility/SigningUtility.cs.meta
Labels: enhancement, fix

#779 Correct Window Initialization & Window Title
  Assets/Plugins/Source/Editor/EditorWindows/CheckDeploymentWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/CreatePackageWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSEditorWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSPluginSettingsWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSSettingsWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/InstallEOSZipWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/LogLevelWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/PluginVersionWindow.cs
Labels: enhancement, UI

#778 feat: Add ability configure the plugin to not unload the EOS SDK on shutdown.
  Assets/Plugins/Source/Core/EOSManager.cs
  docs/c_sharp_defines.md
Labels: enhancement, fix

#782 Upgrade Unity Version
  .github/workflows/unity-version-badge.yml
  Packages/packages-lock.json
  ProjectSettings/ProjectVersion.txt
  README.md
  com.playeveryware.eos/README.md
  com.playeveryware.eos/package.json
  docs/android/environment_setup_android.md
  docs/macOS/README_macOS.md
  docs/supported_platforms.md
  docs/supported_versions_of_unity.md
  docs/unity_specific.md
  tools/scripts/setup-linux.sh
Labels: enhancement, build

#786 Fix Workflow
  .github/workflows/unity-version-badge.yml
Labels: bug

#792 fix(android,fileIO) : remove file check that prevent file reading on android
  Assets/Plugins/Source/Core/Config.cs
Labels: bug, enhancement, fix

#793 Fix log level native
  Assets/Plugins/Windows/x64/DynamicLibraryLoaderHelper-x64.dll
  Assets/Plugins/Windows/x64/GfxPluginNativeRender-x64.dll
  Assets/Plugins/Windows/x86/DynamicLibraryLoaderHelper-x86.dll
  Assets/Plugins/Windows/x86/GfxPluginNativeRender-x86.dll
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/dllmain.cpp
Labels: enhancement, fix

#794 Fix EAC post build for Mac
  Assets/Plugins/Source/Editor/Configs/ToolsConfig.cs
  etc/PlatformSpecificAssets/EOS/Mac/EasyAntiCheat/Settings.json
  tools/bin/EAC/Mac/anticheat_integritytool
Labels: enhancement, fix

#790 refactor(sessions): Adding Friends UI Tab to Sessions
  Assets/Scenes/StandardSamples/SessionsAndMatchmaking.unity
  Assets/Scripts/EOSFriendsManager.cs
  Assets/Scripts/EOSSessionsManager.cs
  Assets/Scripts/P2PNetcodeSample/UI/P2PNetcode/UIP2PTransportMenu.cs
  Assets/Scripts/StandardSamples/UI/CustomInvites/UICustomInvitesMenu.cs
  Assets/Scripts/StandardSamples/UI/Friends/UIFriendInteractionSource.cs
  Assets/Scripts/StandardSamples/UI/Friends/UIFriendsMenu.cs
  Assets/Scripts/StandardSamples/UI/Lobbies/UILobbiesMenu.cs
  Assets/Scripts/StandardSamples/UI/MatchMaking/UISessionsMatchmakingMenu.cs
Labels: enhancement, UI

#799 fix: Prevent placeholder `.meta` files from being deleted.
  com.playeveryware.eos/Editor/.gitignore
  com.playeveryware.eos/Images/.gitignore
Labels: enhancement, build, fix

#805 fix: Trailing `null` characters in parsing of downloaded file.
  Assets/Scripts/EOSPlayerDataStorageManager.cs
  Assets/Scripts/EOSTitleStorageManager.cs
Labels: fix

#807 fix: Add to `.gitignore` to avoid init scene being added during unit testing
  .gitignore
Labels: enhancement

#809 Fix Custom Mapping Enum Tests
  Assets/Plugins/Source/Core/Utility/Extensions/PlatformFlagsExtensions.cs
  Assets/Tests/PlayMode/ClientSessionTests.cs
  Assets/Tests/PlayMode/Utility.meta
  Assets/Tests/PlayMode/Utility/Extensions.meta
  Assets/Tests/PlayMode/Utility/Extensions/AuthScopeFlagsExtensionsTests.cs
  Assets/Tests/PlayMode/Utility/Extensions/AuthScopeFlagsExtensionsTests.cs.meta
  Assets/Tests/PlayMode/Utility/Extensions/CustomMappedEnumTestBase.cs
  Assets/Tests/PlayMode/Utility/Extensions/CustomMappedEnumTestBase.cs.meta
  Assets/Tests/PlayMode/Utility/Extensions/IntegratedPlatformManagementFlagsExtensionsTests.cs
  Assets/Tests/PlayMode/Utility/Extensions/IntegratedPlatformManagementFlagsExtensionsTests.cs.meta
  Assets/Tests/PlayMode/Utility/Extensions/PlatformFlagsExtensionsTests.cs
  Assets/Tests/PlayMode/Utility/Extensions/PlatformFlagsExtensionsTests.cs.meta
  Assets/Tests/PlayMode/Utility/SafeTranslatorTests.cs
  Assets/Tests/PlayMode/Utility/SafeTranslatorTests.cs.meta
Labels: enhancement, fix

#808 fix: Consolidate test functionality of client sessions tests.
  Assets/Tests/Common/EOSTestBase.cs
  Assets/Tests/PlayMode/ClientSessionTests.cs
Labels: enhancement
