Repository PlayEveryWare/eos_plugin_for_unity, pull requests merged in 2024-06, with the labels that each got.

#648 Correct `MacOSBuilder`'s `PreBuild` step
  Assets/Plugins/macOS/Editor/MacOSBuilder.cs
Labels: fix

#703 fix (EAC): Replace text replacement strings
  etc/PlatformSpecificAssets/EOS/Linux/EasyAntiCheat/Settings.json
  etc/PlatformSpecificAssets/EOS/Mac/EasyAntiCheat/Settings.json
  etc/PlatformSpecificAssets/EOS/Windows/EasyAntiCheat/Settings.json
Labels: bug

#708 Upgrade Android Gradle Dependencies
  etc/PlatformSpecificAssets/EOS/Android/eos_dependencies.androidlib/build.gradle
Labels: fix

#711 Relocate `TryGetTempDirectory` function to `FileUtility` from `PackageFileUtility`
  Assets/Plugins/Source/Core/Utility/FileUtility.cs
  Assets/Plugins/Source/Editor/Utility/BuildUtility.cs
  Assets/Plugins/Source/Editor/Utility/PackageFileUtility.cs
  Assets/Plugins/Source/Editor/Utility/UnityPackageCreationUtility.cs
  Assets/Plugins/Source/Editor/Windows/InstallEOSZipWindow.cs
Labels: enhancement

#713 QOL: Smooth progress bar
  Assets/Plugins/Source/Editor/Windows/CreatePackageWindow.cs
Labels: enhancement, UI

#712 Relocate file copy operations from `PackageFileUtility` to `FileUtility`
  Assets/Plugins/Source/Core/Utility/Extensions/ListExtensions.cs
  Assets/Plugins/Source/Core/Utility/Extensions/ListExtensions.cs.meta
  Assets/Plugins/Source/Core/Utility/FileUtility.cs
  Assets/Plugins/Source/Editor/Utility/PackageFileUtility.cs
  Assets/Plugins/Source/Editor/Utility/UnityPackageCreationUtility.cs
  Assets/Plugins/Source/Editor/Windows/CreatePackageWindow.cs
Labels: enhancement, fix

#714 Package creation and `.meta` files
  Assets/Plugins/Source/Core/Utility/Extensions/FileInfoExtensions.cs
  Assets/Plugins/Source/Core/Utility/FileUtility.cs
  Assets/Plugins/Source/Editor/Build/BuildPackage.cs
  Assets/Plugins/Source/Editor/Utility/PackageFileUtility.cs
  Assets/Plugins/Source/Editor/Utility/UnityPackageCreationUtility.cs
  Assets/Plugins/Source/Editor/Windows/CreatePackageWindow.cs
  etc/PackageConfigurations/eos_package_description.json
Labels: enhancement, build

#716 Threaded File Copy (aka ~5x Speed Boost in Package Creation)
  Assets/Plugins/Source/Core/Utility/FileUtility.cs
Labels: enhancement, build

#717 chore: Add logging to confirm that upon retrying a file that previous…
  Assets/Plugins/Source/Core/Utility/FileUtility.cs
Labels: enhancement

#718 fix: Remove extra file copy operation
  Assets/Plugins/Source/Core/Utility/FileUtility.cs
Labels: enhancement

#719 fix: Minor corrections to `CreatePackageWindow`
  Assets/Plugins/Source/Editor/Windows/CreatePackageWindow.cs
Labels: enhancement

#720 fix: Make `Config.Get` and `Config.GetAsync` compatible with Android
  Assets/Plugins/Source/Core/Config.cs
Labels: bug, fix

#722 fix: Correct implementation of `ReadAllTextAsync` for Android
  Assets/Plugins/Source/Core/Utility/FileUtility.cs
Labels: enhancement, fix

#725 `EOSAchievementManager` refactor (Precursor to introduction of `StatsManager`)
  Assets/Scripts/EOSAchievementManager.cs
  Assets/Scripts/UI/Achievements/UIAchievementsMenu.cs
Labels: documentation, enhancement

#721 fix: Enable Recursive File Selection during Package Creation
  Assets/Plugins/Source/Editor/Utility/PackageFileUtility.cs
  etc/PackageConfigurations/eos_package_description.json
Labels: enhancement, build, fix

#729 Release 3.2.1 (changes into `development`)
  Assets/Plugins/Source/Core/EOSPackageInfo.cs
  etc/PackageTemplate/package.json
Labels: enhancement

#733 Correct a misplaced `#endif`
  Assets/Plugins/Source/Core/Utility/FileUtility.cs
Labels: fix

#728 Introduction of `StatsManager`
  Assets/Scripts/EOSAchievementManager.cs
  Assets/Scripts/EOSLeaderboardManager.cs
  Assets/Scripts/ServiceManagers.meta
  Assets/Scripts/ServiceManagers/ServiceManager.cs
  Assets/Scripts/ServiceManagers/ServiceManager.cs.meta
  Assets/Scripts/ServiceManagers/StatsManager.cs
  Assets/Scripts/ServiceManagers/StatsManager.cs.meta
  Assets/Scripts/UI/Achievements/UIAchievementsMenu.cs
  Assets/Scripts/UI/Leaderboard/UILeaderboardMenu.cs
  etc/PackageConfigurations/eos_package_description.json
Labels: enhancement

#724 fix(mac) : Update burst to resolve persistent login crashing issue
  Packages/manifest.json
  Packages/packages-lock.json
Labels: enhancement, fix

#735 Rename recently refactored 'Manager' classes to be 'Service' classes.
  Assets/Scripts/AchievementsService.cs
  Assets/Scripts/AchievementsService.cs.meta
  Assets/Scripts/NamingConventionReadMe.txt
  Assets/Scripts/Services.meta
  Assets/Scripts/Services/EOSService.cs
  Assets/Scripts/Services/EOSService.cs.meta
  Assets/Scripts/Services/StatsService.cs
  Assets/Scripts/Services/StatsService.cs.meta
  Assets/Scripts/UI/Achievements/UIAchievementsMenu.cs
  Assets/Scripts/UI/Leaderboard/UILeaderboardMenu.cs
Labels: enhancement

#737 Combine `IEOSAuthOnLogin` and `IEOSAuthOnLogout` into `IAuthInterfaceEventListener` interface.
  Assets/Plugins/Source/Core/EOSManager.cs
  Assets/Plugins/Source/Core/IAuthInterfaceEventListener.cs
  Assets/Plugins/Source/Core/IAuthInterfaceEventListener.cs.meta
  Assets/Plugins/Source/Core/IConnectInterfaceEventListener.cs
  Assets/Plugins/Source/Core/IConnectInterfaceEventListener.cs.meta
  Assets/Scripts/EOSAntiCheatClientManager.cs
  Assets/Scripts/EOSMetricsManager.cs
  Assets/Scripts/EOSStoreManager.cs
  Assets/Scripts/EOSUserInfoManager.cs
  Assets/Scripts/Services/EOSService.cs
  Assets/Scripts/UI/Common/UIDisplayName.cs
Labels: enhancement

#744 Hotfixes for Release `3.2.1`
  Assets/Plugins/Source/Core/EOSManager.cs
  Assets/Plugins/Source/Core/EOSPackageInfo.cs
  CHANGELOG.md
  etc/PackageTemplate/CHANGELOG.md
  etc/PackageTemplate/package.json
Labels: bug, fix

#743 Correct `!EOS_DISABLE` scripting defines
  Assets/Plugins/Source/Core/EOSManager.cs
  Assets/Plugins/Windows/Editor/WindowsBuilder.cs
Labels: bug

#747 Package Description Fix
  etc/PackageConfigurations/eos_package_description.json
Labels: fix

#746 Modest improvements to `UnityProjectUtility`
  Assets/Plugins/Source/Editor/Utility/UnityProjectUtility.cs
Labels: enhancement

#751 Log Filter
  Assets/Plugins/Source/Editor/Utility/LogUtility.cs
  Assets/Plugins/Source/Editor/Utility/LogUtility.cs.meta
Labels: enhancement, build

#726 Steam login with `GetAuthTicketForWebApi `
  Assets/Scripts/Steam/SteamManager.cs
Labels: bug, enhancement, fix

#750 Release Tasks
  CHANGELOG.md
  etc/PackageTemplate/CHANGELOG.md
Labels: enhancement
