Repository PlayEveryWare/eos_plugin_for_unity, pull requests merged in 2025-02, with the labels that each got.

#1058 fix: Properly wait for client to accept connection
  Assets/Scripts/P2PNetcodeSample/Networking/EOSTransportManager.cs
Labels: fix, tracked

#1119 feat(upm,tool) : upm multi package build window
  Assets/Plugins/Source/Editor/EditorWindows/BatchBuilder.cs
  Assets/Plugins/Source/Editor/EditorWindows/BatchBuilder.cs.meta
  Assets/Plugins/Source/Editor/Utility/UnityPackageCreationUtility.cs
Labels: enhancement, tracked

#1116 feat: User experience for entering invalid product version.
  Assets/Plugins/Source/Editor/Utility/GUIEditorUtility.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/ConfigFieldAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/Validators.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes/Validators/FieldValidator.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/Validators/FieldValidator.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes/Validators/FieldValidatorAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/Validators/FieldValidatorAttribute.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes/Validators/GUIDFieldValidatorAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/Validators/GUIDFieldValidatorAttribute.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes/Validators/LengthValidationAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/Validators/LengthValidationAttribute.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes/Validators/NonEmptyStringFieldValidatorAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/Validators/NonEmptyStringFieldValidatorAttribute.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes/Validators/README.md
  com.playeveryware.eos/Runtime/Core/Config/Attributes/Validators/README.md.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes/Validators/RegexValidationAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/Validators/RegexValidationAttribute.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes/Validators/SandboxIDFieldValidatorAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/Validators/SandboxIDFieldValidatorAttribute.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/Attributes/Validators/StringValidationAttribute.cs
  com.playeveryware.eos/Runtime/Core/Config/Attributes/Validators/StringValidationAttribute.cs.meta
  com.playeveryware.eos/Runtime/Core/Config/ProductConfig.cs
Labels: bug, fix, tracked

#1051 fix: Implement distinction between authentication on different interfaces within EOS SDK.
  Assets/Scripts/Common.meta
  Assets/Scripts/StandardSamples/Services/AchievementsService.cs
  Assets/Scripts/StandardSamples/Services/EOSService.cs
  Assets/Scripts/StandardSamples/Services/PlayerDataStorageService.cs
  Assets/Scripts/StandardSamples/Services/StatsService.cs
  Assets/Scripts/StandardSamples/UI/Common/SampleMenu.cs
  com.playeveryware.eos/Runtime/Core/Authentication.meta
  com.playeveryware.eos/Runtime/Core/Authentication/AuthenticationChangedEventArgs.cs
  com.playeveryware.eos/Runtime/Core/Authentication/AuthenticationChangedEventArgs.cs.meta
  com.playeveryware.eos/Runtime/Core/Authentication/AuthenticationEventDispatcher.cs
  com.playeveryware.eos/Runtime/Core/Authentication/AuthenticationEventDispatcher.cs.meta
  com.playeveryware.eos/Runtime/Core/Authentication/AuthenticationEventObserver.cs
  com.playeveryware.eos/Runtime/Core/Authentication/AuthenticationEventObserver.cs.meta
  com.playeveryware.eos/Runtime/Core/Authentication/LoginInterfaces.cs
  com.playeveryware.eos/Runtime/Core/Authentication/LoginInterfaces.cs.meta
  com.playeveryware.eos/Runtime/Core/Common/Disposable.cs
  com.playeveryware.eos/Runtime/Core/Common/Disposable.cs.meta
Labels: enhancement, tracked
