Repository PlayEveryWare/eos_plugin_for_unity, pull requests merged in 2025-01, with the labels that each got.

#1076 fix: Use `PresenceVal.isOn` while calling `CreateSession`
  Assets/Scripts/StandardSamples/UI/MatchMaking/UISessionsMatchmakingMenu.cs
Labels: fix, tracked

#1077 fix(mac) : remove extra arguments in platformspecifics
  Assets/Plugins/Android/Core/AndroidPlatformSpecifics.cs
  Assets/Plugins/Linux/Core/LinuxPlatformSpecifics.cs
  Assets/Plugins/iOS/Core/IOSPlatformSpecifics.cs
  Assets/Plugins/macOS/Core/MacOSPlatformSpecifics.cs
Labels: bug, fix

#1078 fix: Auto Select Only Client Credential and Deployment During Migration
  com.playeveryware.eos/Runtime/Core/Config/PlatformConfig.cs
Labels: fix, tracked

#1080 feat: Enable PlatformConfigs to Provide Default `IntegratedPlatformManagementFlags`
  com.playeveryware.eos/Runtime/Core/Config/PlatformConfig.cs
Labels: enhancement, tracked

#1081 fix: Restore Steam Integration
  Assets/Plugins/Windows/x64/DynamicLibraryLoaderHelper-x64.dll
  Assets/Plugins/Windows/x64/GfxPluginNativeRender-x64.dll
  Assets/Plugins/Windows/x86/DynamicLibraryLoaderHelper-x86.dll
  Assets/Plugins/Windows/x86/GfxPluginNativeRender-x86.dll
  lib/NativeCode/DynamicLibraryLoaderHelper/Directory.Build.props
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/NativeRender.vcxproj
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/include/Config/SteamConfig.hpp
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/include/string_helpers.h
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/pch.h
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/scripts/prebuild.ps1
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/src/eos_helpers.cpp
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/src/string_helpers.cpp
Labels: fix, tracked

#1079 fix: Add config editors for all platforms
  com.playeveryware.eos/Runtime/Core/Common/Utility/ReflectionUtility.cs
  com.playeveryware.eos/Runtime/Core/Common/Utility/ReflectionUtility.cs.meta
  com.playeveryware.eos/Runtime/Core/PlatformManager.cs
Labels: fix, tracked

#1083 fix: Nullsafe ThreadAffinity
  lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/include/Config/PlatformConfig.hpp
Labels: tracked

#1087 fix: Make first time user experience clearer.
  Assets/Plugins/Source/Editor/Utility/GUIEditorUtility.cs
Labels: enhancement, fix, release

#1089 fix: Resolve race conditions for file IO.
  Assets/Plugins/Source/Editor/ConfigEditors/ConfigEditor.cs
  Assets/Plugins/Source/Editor/ConfigEditors/IConfigEditor.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSPluginSettingsWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSSettingsWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSSettingsWindow_DEPRECATED.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSUnitTestSettingsWindow.cs
  com.playeveryware.eos/Runtime/Core/Utility/FileSystemUtility.cs
Labels: enhancement, fix, tracked, release

#1091 chore: Correct the name of `EOSSettingsWindow` to omit the `NEW_` prefix
  Assets/Plugins/Source/Editor/EditorWindows/EOSSettingsWindow.cs
Labels: enhancement, fix, tracked, release

#1092 chore: Default to not show unavailable platforms in `EOSSettingsWindow`.
  Assets/Plugins/Source/Editor/EditorWindows/EOSSettingsWindow.cs
Labels: enhancement, fix, tracked, release

#1085 fix: Set default deployment and sandbox values for platforms for first-time user scenarios
  Assets/Plugins/Source/Editor/ConfigEditors/IPlatformConfigEditor.cs
  Assets/Plugins/Source/Editor/ConfigEditors/PlatformConfigEditor.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSEditorWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSSettingsWindow.cs
  Assets/Plugins/Source/Editor/Utility/GUIEditorUtility.cs
  com.playeveryware.eos/Runtime/Core/Common/Named.cs
  com.playeveryware.eos/Runtime/Core/Config/Config.cs
  com.playeveryware.eos/Runtime/Core/Config/Deployment.cs
  com.playeveryware.eos/Runtime/Core/Config/ProductConfig.cs
  com.playeveryware.eos/Runtime/Core/Config/ProductionEnvironments.cs
  com.playeveryware.eos/Runtime/Core/Config/SandboxId.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/EOSClientCredentials.cs
  com.playeveryware.eos/Runtime/Core/PlatformManager.cs
Labels: fix, tracked, release

#1096 fix: Properly auto-select the platform targeted in settings
  Assets/Plugins/Source/Editor/EditorWindows/EOSSettingsWindow.cs
  com.playeveryware.eos/Runtime/Core/PlatformManager.cs
Labels: enhancement, fix, tracked, release

#1095 fix: Client Credential auto-selection
  Assets/Plugins/Source/Editor/ConfigEditors/IPlatformConfigEditor.cs
  Assets/Plugins/Source/Editor/ConfigEditors/PlatformConfigEditor.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSSettingsWindow.cs
  com.playeveryware.eos/Runtime/Core/Config/ProductConfig.cs
Labels: enhancement, fix, tracked, release

#1099 fix: Restore functionality of Unit Tests
  Assets/Plugins/Source/Editor/com.playeveryware.eos-Editor.asmdef
  Assets/Tests/Common/CodeCoverageHistoryCleaner.cs
  Assets/Tests/Common/UnitTestConfig.cs
  Assets/Tests/Common/UnitTestConfig.cs.meta
  Assets/Tests/Common/com.playeveryware.eos.tests.common.asmdef
  com.playeveryware.eos/Runtime/Core/Utility/FileSystemUtility.cs
Labels: enhancement, fix, tracked, release

#1098 fix: `WrappedInitializeThreadAffinity` `null` case
  com.playeveryware.eos/Runtime/Core/Config/PlatformConfig.cs
Labels: enhancement, fix, tracked, release

#1097 fix: Auto select deployment and client credentials for newly introduced platforms
  Assets/Plugins/Source/Editor/EditorWindows/EOSSettingsWindow.cs
  com.playeveryware.eos/Runtime/Core/Config/PlatformConfig.cs
Labels: enhancement, fix, tracked, release

#1101 fix: Complete application of command line arguments from the Epic Games Launcher
  com.playeveryware.eos/Runtime/Core/Config/SandboxId.cs
  com.playeveryware.eos/Runtime/Core/EOSManager.cs
Labels: enhancement, fix, tracked, release

#1107 Release 3.3.5 (into `development`)
  .github/workflows/update-package-description.yml
  Assets/Plugins/Android/login.java.meta
  Assets/Plugins/Source/Editor/ConfigEditors/ConfigEditor.cs
  Assets/Plugins/Source/Editor/ConfigEditors/IConfigEditor.cs
  Assets/Plugins/Source/Editor/ConfigEditors/IPlatformConfigEditor.cs
  Assets/Plugins/Source/Editor/ConfigEditors/PlatformConfigEditor.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSEditorWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSPluginSettingsWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSSettingsWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSSettingsWindow_DEPRECATED.cs
  Assets/Plugins/Source/Editor/EditorWindows/EOSUnitTestSettingsWindow.cs
  Assets/Plugins/Source/Editor/Utility/GUIEditorUtility.cs
  Assets/Plugins/Source/Editor/com.playeveryware.eos-Editor.asmdef
  Assets/Plugins/Windows/x64/EOSSDK-Win64-Shipping.lib
  Assets/Plugins/Windows/x64/EOSSDK-Win64-Shipping.lib.meta
  Assets/Plugins/Windows/x86/EOSSDK-Win32-Shipping.lib
  Assets/Plugins/Windows/x86/EOSSDK-Win32-Shipping.lib.meta
  Assets/Plugins/macOS/MicrophoneUtility_macos.dylib
  Assets/Plugins/macOS/libDynamicLibraryLoaderHelper.dylib
  Assets/Scripts/P2PNetcodeSample/UI/P2PNetcode/UIP2PTransportMenu.cs
  Assets/Scripts/StandardSamples/SignInWithGoogle/login.java
  Assets/Scripts/StandardSamples/SignInWithGoogle/login.java.meta
  Assets/Tests/Common/CodeCoverageHistoryCleaner.cs
  Assets/Tests/Common/UnitTestConfig.cs
  Assets/Tests/Common/UnitTestConfig.cs.meta
  Assets/Tests/Common/com.playeveryware.eos.tests.common.asmdef
  Assets/Tests/PlayMode/Config/EOSConfigTests.cs
  com.playeveryware.eos/CHANGELOG.md
  com.playeveryware.eos/Documentation~/configure_plugin.md
  com.playeveryware.eos/Documentation~/images/dev-portal-configuration-editor-menu.png
  com.playeveryware.eos/Documentation~/images/eos-configuration-menu.png
  com.playeveryware.eos/Documentation~/images/eos_configuration.png
  com.playeveryware.eos/Images.meta
  com.playeveryware.eos/Images/.gitignore
  com.playeveryware.eos/Runtime/Core/Common/Named.cs
  com.playeveryware.eos/Runtime/Core/Config/Config.cs
  com.playeveryware.eos/Runtime/Core/Config/Deployment.cs
  com.playeveryware.eos/Runtime/Core/Config/EOSConfig.cs
  com.playeveryware.eos/Runtime/Core/Config/PlatformConfig.cs
  com.playeveryware.eos/Runtime/Core/Config/ProductConfig.cs
  com.playeveryware.eos/Runtime/Core/Config/ProductionEnvironments.cs
  com.playeveryware.eos/Runtime/Core/Config/SandboxId.cs
  com.playeveryware.eos/Runtime/Core/EOSManager.cs
  com.playeveryware.eos/Runtime/Core/EOSPackageInfo.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/EOSClientCredentials.cs
  com.playeveryware.eos/Runtime/Core/PlatformManager.cs
  com.playeveryware.eos/Runtime/Core/Utility/FileSystemUtility.cs
  com.playeveryware.eos/Samples.meta
  com.playeveryware.eos/Samples/.gitignore
  com.playeveryware.eos/package.json
  etc/PackageConfigurations/eos_package_description.json
  etc/PlatformSpecificAssets/EOS/Android/dynamic-stdc++/aar/eos-sdk.aar
  etc/PlatformSpecificAssets/EOS/Android/static-stdc++/aar/eos-sdk.aar
Labels: enhancement, tracked, release

#1082 feat: ExecuteQueuedMainThreadTasks
  com.playeveryware.eos/Runtime/Core/EOSManager.cs
Labels: tracked

#1109 fix: Smarter Enum Conversion
  Assets/Tests/PlayMode/Config/JsonConverters/ListOfStringsToEnumConverterTests.cs
  com.playeveryware.eos/Runtime/Core/Common/Utility/EnumUtility.cs
  com.playeveryware.eos/Runtime/Core/Config/JsonConverter/ListOfStringsToEnumConverters.cs
Labels: enhancement, fix, tracked

#1105 feat: Display & Make editable the Encryption Key for Client Credentials
  Assets/Plugins/Source/Editor/EditorWindows/EOSEditorWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/EncryptionKeyWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/EncryptionKeyWindow.cs.meta
  Assets/Plugins/Source/Editor/EditorWindows/ModalEOSEditorWindow.cs
  Assets/Plugins/Source/Editor/EditorWindows/ModalEOSEditorWindow.cs.meta
  Assets/Plugins/Source/Editor/Utility/GUIEditorUtility.cs
  com.playeveryware.eos/Runtime/Core/EOS_SDK_Additions/EOSClientCredentials.cs
Labels: enhancement, fix, tracked
